auto_conf: False
resume: False
resume_checkpoint: 20

data:
  dir_path: "/home/pranish/pranav/diffusion-mp/simple_diffusion/"
  train_path: "test_datasets/new_elites"
  # train_path: "datasets/xml_29dof/rl_test"
  # task_list_path: "test_datasets/chosen_tasks_test.yml"
  dataset_class: "flexible"
  batch_size: 1024
  num_features: 50
  num_task_params: 2
  num_observations: 45
  start_timestep: 0
  num_timesteps: 5
  state_history: 1
  normalize_goal_vec: True

model:
  type: "dfot"
  backbone_type: "dit1d"
  inpaint: False
  state_condition: True
  task_condition: True
  external_cond_dropout: 0.05
  hidden_size: 256
  depth: 6
  num_heads: 4
  mlp_ratio: 2.0
  pos_emb_type: "sinusoidal_1d"

training:
  save_dir: "./runs/ablations/exp1/"
  log_dir: "./logs/ablations/exp1/"
  suffix: ""
  num_epochs: 2500
  batches_per_epoch: 256
  balance_task_density: False
  learning_rate: 0.0005
  save_every: 10
  condition_dropout_prob: 
    state: 0.1
    task: 0.2
  add_obs_noise: True
  add_goal_noise: False
  state_conditioning_noise_level:
    joints: 0.025
    body_z: 0.025
    body_rot6d: 0.025
    obj_rel_pos: 0.005
    obj_rel_rot6d: 0.005
    # joint_vel: 0.2
    # body_lin_vel: 0.1
    # body_ang_vel: 0.1
    # obj_lin_vel: 0.1
    # obj_ang_vel: 0.1
    task_params: 0.02

noise_scheduler:
  deterministic_inference: True
  train_timesteps: 500
  inference_timesteps: 20
  prediction_type: "v_prediction"
  beta_schedule: "squaredcos_cap_v2" 
  noise_level: "random_independent"
  scheduling_matrix: "full_sequence"
  use_causal_mask: False
  variable_context: True
