auto_conf: False
resume: False
resume_checkpoint: 240

data:
  dir_path: "/home/pranish/pranav/diffusion-mp/simple_diffusion/"
  train_path: "test_datasets/Box_Height_FoLM"
  batch_size: 256
  num_features: 48
  num_task_params: 1
  num_observations: 45
  start_timestep: 0
  num_timesteps: 561
  state_history: 1

model:
  type: "dfot"
  backbone_type: "dit1d"
  state_condition: True
  task_condition: True
  external_cond_dropout: 0.02
  hidden_size: 256
  depth: 12
  num_heads: 8
  mlp_ratio: 4.0
  pos_emb_type: "sinusoidal_1d"

noise_scheduler:
  deterministic_inference: True
  train_timesteps: 400
  inference_timesteps: 20
  prediction_type: "v_prediction"
  beta_schedule: "squaredcos_cap_v2" 
  return_steps: False

training:
  save_dir: "./runs/"
  log_dir: "./logs/"
  suffix: "_diffusion_generator"
  num_epochs: 5000
  batches_per_epoch: 512
  learning_rate: 0.0005
  save_every: 20
  condition_dropout_prob: 
    state: 0.1
    task: 0.1
  add_obs_noise: False
  add_goal_noise: False
  state_conditioning_noise_level:
    joints: 0.01
    body_z: 0.01
    body_rot6d: 0.02
    obj_rel_pos: 0.01
    obj_rel_rot6d: 0.02
    # joint_vel: 0.2
    # body_lin_vel: 0.1
    # body_ang_vel: 0.1
    # obj_lin_vel: 0.1
    # obj_ang_vel: 0.1
    task_params: 0.02
